config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'wallets#index', as: :authenticated_root

      resource :wallets
    end

    unauthenticated :user do
      root to: 'home#index', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :wallets, dependent: :destroy
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user

  validates :address,
            presence: true,
            uniqueness: { scope: :user_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @count = Queries::Wallets::ActiveCount.run.to_i
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  # GET /wallets
  def index
    addresses = ::Queries::Wallets::AddressesList.run!(user: current_user)
    outcome = ::Commands::Wallets::Index.run(addresses: addresses)

    if outcome.success?
      @wallets = outcome.result
    else
      flash.now[:error] = outcome.errors.message_list.join(',')

      @wallets = []
    end
  end

  # GET /wallets/1
  def show
    outcome = ::Commands::Wallets::Show.run(address: account_params)

    if outcome.success?
      @address = account_params
      @balance = outcome.result[:balance]
      @count = outcome.result[:transactions_count]
      @transactions = outcome.result[:transactions]
    else
      flash.now[:error] = outcome.errors.message_list.join(',')
    end
  end

  def new; end

  # POST /wallets
  def create
    outcome = ::Commands::Wallets::Create.run(user: current_user, address: wallet_params['address'])

    if outcome.success?
      redirect_to authenticated_root_path
    else
      flash.now[:error] = outcome.errors.message_list.join(',')

      render('new', status: :bad_request)
    end
  end

  # DELETE /wallets/1
  def destroy
    Wallet.find_by(address: params['format']).destroy

    redirect_to authenticated_root_path
  end

  private

  def wallet_params
    params.require(:wallets).permit(:address)
  end

  def account_params
    params.require(:account)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.home
  %h1 CryptoWallet
  %p Serving #{@count} active wallets

  = link_to 'LOGIN NOW', new_user_session_path, class: 'button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CryptoWallet
    %link{href: "//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic", rel: "stylesheet"}/
    %link{href: "//cdn.rawgit.com/necolas/normalize.css/master/normalize.css", rel: "stylesheet"}/
    %link{href: "//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css", rel: "stylesheet"}/
    %link{crossorigin: "anonymous", href: "https://use.fontawesome.com/releases/v5.3.1/css/all.css", integrity: "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU", rel: "stylesheet"}/

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'

  %body
    .container
      .layout
        .layout__notifications
          - if notice
            .notification.is-info= notice
          - if alert
            .notification.is-warning= alert
        .layout__content
          = yield

app/views/wallets/index.html.haml
- if user_signed_in?
  = link_to('Logout', destroy_user_session_path, method: :delete, class: 'button--logout')
- else
  = link_to('Login', new_user_session_path, class: 'button--logout')
%h1 Hello #{current_user.email}
%p Please find list of your monitored wallets attached

%table
  %thead
    %tr
      %th Wallet address
      %th Number of transactions
      %th Balance
      %th
  - if @wallets.present?
    - @wallets.each do |wallet|
      %tbody
        %tr
          %td= wallet[:account]
          -# TODO: Get real count value
          %td 4
          %td= "#{wallet[:balance]} ETH"
          %td= link_to 'Show', wallets_path(account: wallet[:account])
= link_to 'Add Wallet', new_wallets_path, class: 'button'

app/views/wallets/new.html.haml
.layout__content
  %h2 Create wallet
  %label Wallet address

  - if flash[:error].present?
    = flash[:error]

  = simple_form_for(:wallets, url: wallets_path) do |f|
    %br/
    = f.input :address, label: false
    = f.button :submit, "Add Wallet"

app/views/wallets/show.html.haml
- if user_signed_in?
  = link_to('Logout', destroy_user_session_path, method: :delete, class: 'button--logout')
- else
  = link_to('Login', new_user_session_path, class: 'button--logout')
%h3 Transactions for #{@address}

.row.stats
  .column
    %strong Summary:
  .column
    %strong= @count
    Transactions
  .column
    %strong #{@balance} ETH
    Balance

%table
  %thead
    %tr
      %th Details
      %th Amount (ETH)
      %th Fee (ETH)
      %th Date
  %tbody
    - @transactions.each do |tran|
      - if tran[:from] == @address
        %tr.transaction-outcoming
          %td
            %i.fas.fa-arrow-down
            Transfer to
            = tran[:to]
          %td #{tran[:amounth]} ETH
          %td #{tran[:fee]} ETH
          %td= tran[:diff]
      - else
        %tr.transaction-incoming
          %td
            %i.fas.fa-arrow-up
            Transfer from
            = tran[:from]
          %td #{tran[:amounth]} ETH
          %td #{tran[:fee]} ETH
          %td= tran[:diff]
= button_tag "Change currency to PLN", onclick: "changeCurrency()", class: 'button'
= link_to 'Back to your wallets', authenticated_root_path
|
= button_to 'Remove wallet', wallets_path(@address), method: 'delete'